"""empty message

Revision ID: fc13bfdb2258
Revises: 07d3ae53ca0e
Create Date: 2023-10-18 05:46:24.143282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc13bfdb2258'
down_revision = '07d3ae53ca0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=True),
    sa.Column('passwordHash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=25), nullable=True),
    sa.Column('lastName', sa.String(length=25), nullable=True),
    sa.Column('phoneNumber', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitor')
    op.drop_table('staff')
    # ### end Alembic commands ###
